import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next' 
import TawkTo from '@/components/TawkTo';
 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative bg-white">
        {/* <Navbar /> */}
        {children}
        {/* <TawkTo /> */}
      </body>
    </html>
  )
}
